services:
    visual_craft_beanstalk_scheduler.abstract_scheduler:
        abstract: true
        calls:
          - [setLogger, ["@logger"]]
        tags:
            - { name: monolog.logger, channel: visual_craft_beanstalk_scheduler }

    visual_craft_beanstalk_scheduler.abstract_manager:
        abstract: true
        calls:
          - [setLogger, ["@logger"]]
        tags:
            - { name: monolog.logger, channel: visual_craft_beanstalk_scheduler }

    visual_craft_beanstalk_scheduler.command.clear_queue:
        class: VisualCraft\Bundle\BeanstalkSchedulerBundle\Command\ClearQueueCommand
        calls:
            ['setContainer', ['@container']]
        tags:
            - { name: console.command }

    visual_craft_beanstalk_scheduler.command.run_scheduler:
        class: VisualCraft\Bundle\BeanstalkSchedulerBundle\Command\RunSchedulerCommand
        calls:
            ['setContainer', ['@container']]
        tags:
            - { name: console.command }
